README.md, scoring/docs/terminology.md
Document many of the terms that we use, especially the grouping of teams.
=> Add terminology documentation

scoring/src/fll/web/report/SummarizePhase1.java
=> Sort summarizePhase1.jsp's data

Changes.md, scoring/web/report/finalist/finalist.js, scoring/web/report/finalist/schedule.html, scoring/web/report/finalist/schedule.js
=> Add the number of categories being judged in to the finalist schedule

Changes.md, scoring/src/fll/Launcher.java, scoring/src/fll/scheduler/SchedulerUI.java, scoring/src/fll/subjective/SubjectiveFrame.java, scoring/src/fll/util/GuiExceptionHandler.java, scoring/test-integration/fll/web/ReplayTournament.java
One needs to register the exception handler in 2 places to make sure
that all uncaught exceptions are caught and appropriate action is taken.
Fixes #578
=> Make sure to handle exceptions in the event dispatch thread

Changes.md, Jenkinsfile, scoring/src/fll/documents/writers/SubjectivePdfWriter.java, scoring/src/fll/scheduler/TournamentSchedule.java, scoring/src/fll/web/BlankSubjectiveSheet.java, scoring/web/index.jsp
Allow blank subjective score sheets to be created from the web interface like the blank performance score sheet.
Fixes #426
=> Blank subjective sheets

Changes.md, scoring/src/fll/Tournament.java, scoring/src/fll/db/ImportDB.java, scoring/src/fll/documents/writers/SubjectivePdfWriter.java, scoring/src/fll/resources/subjective.xsd, scoring/src/fll/scheduler/SchedulerUI.java, scoring/src/fll/scheduler/TournamentSchedule.java, scoring/src/fll/subjective/SubjectiveFrame.java, scoring/src/fll/web/BlankSubjectiveSheet.java, scoring/src/fll/web/admin/DisplayTournamentAssignments.java, scoring/src/fll/web/admin/DownloadSubjectiveData.java, scoring/src/fll/web/admin/Tournaments.java, scoring/src/fll/web/developer/importdb/CreateTournament.java, scoring/src/fll/web/playoff/ScoresheetGenerator.java, scoring/src/fll/web/report/CategoryScoresByScoreGroup.java, scoring/src/fll/web/report/FinalComputedScores.java, scoring/src/fll/web/report/PerformanceScoreReport.java, scoring/src/fll/web/report/PlayoffReport.java, scoring/web/admin/index.jsp
Add tournament name to subjective and performance score sheets.
=> Add tournament name score sheets

Changes.md, scoring/src/fll/db/GlobalParameters.java, scoring/src/fll/web/admin/ChangeParameters.java, scoring/src/fll/web/admin/GatherParameterInformation.java, scoring/src/fll/web/playoff/RemoteControlBrackets.java, scoring/src/fll/web/scoreboard/AllTeams.java, scoring/web/admin/edit_all_parameters.jsp, scoring/web/playoff/remoteControlBrackets.jsp
Allow users to control the scroll rate of the all teams part of the score board and the head to head brackets.
=> Configurable scrolling speed

Changes.md, scoring/src/fll/db/GlobalParameters.java, scoring/src/fll/web/admin/ChangeParameters.java, scoring/src/fll/web/admin/GatherParameterInformation.java, scoring/src/fll/web/playoff/RemoteControlBrackets.java, scoring/src/fll/web/scoreEntry/ScoreEntry.java, scoring/src/fll/web/scoreboard/AllTeams.java, scoring/web/admin/edit_all_parameters.jsp, scoring/web/playoff/index.jsp, scoring/web/playoff/remoteControlBrackets.jsp, scoring/web/playoff/scoregenbrackets.js, scoring/web/playoff/scoregenbrackets.jsp, scoring/web/scoreEntry/scoreEntry.css, scoring/web/scoreEntry/scoreEntry.jsp
Align the goal titles to the right to match the printed score sheet
=> Score entry layout

scoring/docs/SetupInstructions.md, scoring/src/fll/db/DumpDB.java, scoring/src/fll/db/ImportDB.java, scoring/src/fll/web/GatherBugReport.java, scoring/test-unit/fll/db/ImportDBTest.java
This takes care of part of issue #616. I still need to figure out a good workflow for importing the data and notifying the user that there are things to look at.
=> Add logs and bug reports to the database dump

scoring/.gitignore, scoring/docs/InstructionsForRunningTheSoftware.md, scoring/src/fll/db/ImportDB.java, scoring/src/fll/web/GatherBugReport.java, scoring/src/fll/web/developer/importdb/ImportDBDump.java, scoring/src/fll/web/setup/CreateDB.java
=> Export logs and bug reports from database being imported

Changes.md, scoring/src/fll/db/ImportDB.java, scoring/src/fll/xml/AbstractGoal.java, scoring/src/fll/xml/XMLUtils.java
Don't check all descendants, just check the direct children.
=> Correctly find the description of a goal

Changes.md, scoring/src/fll/scheduler/TournamentSchedule.java
=> Detailed schedule improvements

Changes.md, scoring/src/fll/db/Queries.java, scoring/src/fll/web/playoff/BracketUpdate.java, scoring/src/fll/web/playoff/H2HUpdateWebSocket.java, scoring/src/fll/web/playoff/ScoresheetGenerator.java, scoring/web/playoff/remoteControlBrackets.js
Fixes #605 and handles deleted scores better
=> Fixes to  head to head display

.classpath
Had hard-coded system reference (jps); made relative.
=> Easy fix to Eclipse classpath

src/main/web/credits/credits.jsp
Figured I'd join the personal website club on the fll-sw credits page :) Have a great season Jon! 😄
=> Add a link to my website in the credits

Changes.md, src/main/java/fll/web/developer/importdb/ImportDBDump.java, src/main/java/fll/web/playoff/Playoff.java, src/main/java/fll/web/scoreEntry/SelectTeam.java, src/main/java/fll/web/scoreEntry/UpdateUnverifiedRuns.java
Add the head to head bracket information to the team selection string.
=> Make team selection easier to read for head to head

Changes.md, src/main/java/fll/web/playoff/H2HUpdateWebSocket.java, src/main/java/fll/web/playoff/Playoff.java, src/main/web/playoff/adminbrackets.js
The initial table assignments from the bracket initialization worked. However tables were not assigned as the brackets moved forward.
=> Table assignment not working in head to head

src/main/java/fll/web/scoreEntry/SelectTeam.java
This happened at the 2022 Minnesota state tournament. This typically happened with teams that are running much later than their scheduled time. I was able to see this happen using the 'All Tables' selection.
=> Teams missing from team selection list

Changes.md, src/main/java/fll/web/scoreboard/Top10.java, src/main/web/report/index.jsp
Just need a link to Top10 with displayAll=true
=> Add link to all performance scores with ranks

Changes.md, src/main/java/fll/scheduler/ScheduleWriter.java, src/main/java/fll/util/FOPUtils.java, src/main/java/fll/web/report/CategoryScoresByScoreGroup.java, src/main/java/fll/web/report/NonNumericNomineesReport.java, src/main/java/fll/web/report/PerformanceScoreReport.java, src/main/java/fll/web/report/PlayoffReport.java, src/main/java/fll/web/report/awards/AwardsReport.java, src/main/java/fll/web/report/awards/AwardsScriptReport.java, src/main/java/fll/web/report/finalist/PdfFinalistSchedule.java, src/main/java/fll/web/report/finalist/TeamFinalistSchedule.java
Top left should show 'After' and the previous presenter. Bottom right should show 'Before' and the next presenter
=> Add before and after presenter to the awards script

Changes.md
Add: "Feedback" to Comments at the bottom of all rubrics so that it now says "Feedback Comments"
Change FLL Logo on all rubrics to new logo - attached
=> Updates to Rubrics
